### ISSUE TITLE
BUG: Wrong default quarter in all searches

### ISSUE THREAD

**Issue by AnikaArora** [ucsb-cs156/proj-courses#95]
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

In all the searches, the default quarter is W22, not the current quarter (S24). 
**Bonus points if you can automate it to update to the current quarter instead of hard-coding S24 in all the forms

### Expected Behavior

In the screenshot below, W22 should be the current quarter (S24). 

### Current / Observed Behavior

<img width="758" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/60118889/9aac8cc4-97eb-48f4-aa38-6250154d96a3">

### Steps to Reproduce

1. Go to any search page on the the main courses site and the default quarter will be W22.

**Comment by pconrad** [comment]
Closing, because this issue is improperly specified.

It is not that the current code has a bug.  Rather, the current code is doing exactly what it is supposed to do.  It's a misunderstanding rather than a bug.

The default quarter is not currently W22.  It's the quarter in local storage, or if there is not, it's the first quarter in the quarter list.

Because the default .env file has only two quarters in it, W22 and S22, it may appear to be the case that the default quarter is W22.  But that's not the case at all.

In fact, there's no bug here to be fixed, and the way students are trying to "fix" it actually breaks an important feature, which is that the site "remembers" your selections in local storage.

If there's anything we might actually want to do, it might be to change the default quarter in the event that there is nothing in local storage to be the "last" quarter in the quarter list instead of the first.  That's more likely to be what the user wants.  I'm going to open a new issue with that as the goal.

That is, whatever the deployment has as the value of END_QTR would be the defacto default quarter (unless the user has selected a different one on a previous search.)

**Comment by pconrad** [comment]
replaced by issue #102
